-- MySQL Script generated by MySQL Workbench
-- Tue Jul 26 13:52:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `Category_ID` INT NOT NULL,
  `Category_title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(300) NULL,
  PRIMARY KEY (`Category_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image_product` (
  `Image_ID` INT NOT NULL,
  `Product_ID` INT NOT NULL,
  `Alt` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Image_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `Product_id` INT NOT NULL,
  `Product_name` VARCHAR(45) NOT NULL,
  `Desription` VARCHAR(45) NULL,
  `Activity` TINYINT(1) NULL,
  `promo_price` INT NULL,
  `price` INT NULL,
  `sale_price` INT NULL,
  `Category_ID` INT NOT NULL,
  `Main_Image_ID` INT NOT NULL,
  PRIMARY KEY (`Product_id`),
  INDEX `fk_Product_Category1_idx` (`Category_ID` ASC) VISIBLE,
  INDEX `fk_Product_Image_product1_idx` (`Main_Image_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_ID`)
    REFERENCES `mydb`.`Category` (`Category_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Image_product1`
    FOREIGN KEY (`Main_Image_ID`)
    REFERENCES `mydb`.`Image_product` (`Image_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category_has_Product` (
  `Category_ID` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`Category_ID`, `Product_id`),
  INDEX `fk_Category_has_Product_Product1_idx` (`Product_id` ASC) VISIBLE,
  INDEX `fk_Category_has_Product_Category1_idx` (`Category_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Category_has_Product_Category1`
    FOREIGN KEY (`Category_ID`)
    REFERENCES `mydb`.`Category` (`Category_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product_has_Image_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_has_Image_product` (
  `Product_id` INT NOT NULL,
  `Image_ID` INT NOT NULL,
  PRIMARY KEY (`Product_id`, `Image_ID`),
  INDEX `fk_Product_has_Image_product_Image_product1_idx` (`Image_ID` ASC) VISIBLE,
  INDEX `fk_Product_has_Image_product_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Image_product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Image_product_Image_product1`
    FOREIGN KEY (`Image_ID`)
    REFERENCES `mydb`.`Image_product` (`Image_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
